### ISSUE TITLE
Videos Try Downloading As PNG

### ISSUE THREAD

**Issue by PlzHlpWithFansly** [Motyldrogi/fansly-downloader#17]
When I try to download video files with this extension, the Windows Explorer window specifies the file type as PNG.  This appears to apply to all video files across multiple different content creators to whom I am subscribed.  I have deleted the extension, redownloaded and extracted (after unblocking the archive), and the problem persists.

**Comment by PlzHlpWithFansly** [comment]
Upon inspection of the extension, there's an error:

Uncaught TypeError:  Cannot read properties of undefined (reading 'split'"

Stack Trace 
content.js.195 (anonymous function)

Points to line 195 in code:
const name = feedUsername + "-" + downloadLink.split("/")[4].split("?")[0];

**Comment by Motyldrogi** [comment]
@PlzHlpWithFansly Hey, you are correct. Fansly updated their website and the downloader is broken now. I will fix it

**Comment by oeks01** [comment]
also is there a way, to add a 'download all' button to download all the content on a post?

**Comment by Motyldrogi** [comment]
@oeks01 It would be possible to implement something like this, but not that good and performant since that is a chrome extension. There is also a python programm which is a bit more complicated to install, but it is well documented. You can find it here: https://github.com/Avnsx/fansly

This is also capable of downloading all the content from a creator.

**Comment by Motyldrogi** [comment]
@PlzHlpWithFansly @oeks01 
I fixed it, new version available here: https://github.com/Motyldrogi/fansly-downloader/releases/tag/2.0.6
