### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Site3op** [Motyldrogi/fansly-downloader#2]
I don't know if it's possible but maybe a way to download all content from a creator in one click?

**Comment by Motyldrogi** [comment]
@Site3op There is already a downloader for all media that I found on reddit: https://www.reddit.com/user/Winter-Elephant-2250/comments/p3j87m/released_fansly_scraper_app_open_source/

It's a command line tool, but since I see on your profile that you have used an onlyfans scraper with python I think you know how it works 😅 There is also a readme file.
